// <auto-generated />
namespace MvcApp1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddingUsersDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingUsersDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201502041151105_AddingUsersDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
